import { Head, router } from '@inertiajs/react';
import { Activity, ChevronLeft, ChevronRight, Filter, History, Search } from 'lucide-react';
import { useMemo, useState } from 'react';
import { OwnerPage, OwnerStatusBadge, ownerControlClass, ownerPanelClass, ownerSecondaryActionClass } from '@/components/owner-ui';
import { Dialog, DialogContent, DialogDescription, DialogTitle } from '@/components/ui/dialog';
import { useAuditRealtimeRefresh } from '@/hooks/use-audit-realtime-refresh';
import { auditTrail } from '@/routes/workspaces';

type Option = { id: string | number; name: string; code?: string; email?: string };
type PageLink = { url: string | null; label: string; active: boolean };
type AuditLog = { id: string; created_at: string; branch: { id: string; name: string; code: string } | null; actor: { id: number; name: string; email: string } | null; module: string; action: string; auditable_type: string; auditable_id: string; before: Record<string, unknown> | null; after: Record<string, unknown> | null; metadata: Record<string, unknown> | null };
type Props = { logs: { data: AuditLog[]; links: PageLink[]; from: number | null; to: number | null; total: number }; filters: Record<string, string>; branches: Option[]; users: Option[]; modules: string[]; actions: string[] };

const dateTime = new Intl.DateTimeFormat('en-PH', { dateStyle: 'medium', timeStyle: 'short', timeZone: 'Asia/Manila' });

export default function AuditTrail({ logs, filters, branches, users, modules, actions }: Props) {
    const [selected, setSelected] = useState<AuditLog | null>(null);
    const [search, setSearch] = useState(filters.search ?? '');
    const realtimeProps = useMemo(() => ['logs', 'modules', 'actions'], []);
    useAuditRealtimeRefresh(realtimeProps);

    const apply = (next: Record<string, string>) => router.get(auditTrail(), { ...filters, ...next }, { preserveScroll: true, replace: true });
    const clear = () => {
        setSearch('');
        router.get(auditTrail(), {}, { preserveScroll: true, replace: true });
    };

    return <><Head title="Audit trail" /><OwnerPage title="Audit trail" description="Live, append-only activity across every branch. New entries appear automatically." action={<OwnerStatusBadge tone="green"><Activity className="mr-1 size-3" /> Live</OwnerStatusBadge>}>
        <section className={`${ownerPanelClass} p-3 md:p-4`}><form className="flex flex-col gap-3" onSubmit={(event) => { event.preventDefault(); apply({ search }); }}><div className="flex flex-col gap-2 sm:flex-row"><label className="relative min-w-0 flex-1"><Search className="pointer-events-none absolute top-1/2 left-3 size-4 -translate-y-1/2 text-neutral-400" /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search action, staff member, or record ID" className={`${ownerControlClass} w-full pl-10`} /></label><button type="submit" className={ownerSecondaryActionClass}>Search</button><button type="button" onClick={clear} className={ownerSecondaryActionClass}>Clear all</button></div><div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-5"><Select label="Branch" value={filters.branch_id ?? ''} options={branches.map((branch) => [String(branch.id), `${branch.name} · ${branch.code}`])} onChange={(branch_id) => apply({ branch_id })} /><Select label="Actor" value={filters.user_id ?? ''} options={users.map((user) => [String(user.id), `${user.name} · ${user.email}`])} onChange={(user_id) => apply({ user_id })} /><Select label="Module" value={filters.module ?? ''} options={modules.map((module) => [module, module])} onChange={(module) => apply({ module })} /><Select label="Action" value={filters.action ?? ''} options={actions.map((action) => [action, action])} onChange={(action) => apply({ action })} /><label className="grid gap-1 text-[11px] font-semibold text-neutral-600">Date<input type="date" value={filters.date ?? ''} onChange={(event) => apply({ date: event.target.value })} className={ownerControlClass} /></label></div></form></section>
        <section className={`${ownerPanelClass} overflow-hidden`}><div className="flex items-center justify-between gap-3 border-b border-neutral-100 px-4 py-3"><div><p className="text-sm font-semibold">Activity feed</p><p className="text-xs text-neutral-500">{logs.total} matching audit entries</p></div><OwnerStatusBadge tone="outline"><Filter className="mr-1 size-3" /> Filters on</OwnerStatusBadge></div>{logs.data.length === 0 ? <EmptyState /> : <div className="divide-y divide-neutral-100">{logs.data.map((log) => <AuditRow key={log.id} log={log} onSelect={setSelected} />)}</div>}<Pagination links={logs.links} /></section>
    </OwnerPage>{selected && <AuditDetail log={selected} onClose={() => setSelected(null)} />}</>;
}

function Select({ label, value, options, onChange }: { label: string; value: string; options: [string, string][]; onChange: (value: string) => void }) { return <label className="grid gap-1 text-[11px] font-semibold text-neutral-600">{label}<select value={value} onChange={(event) => onChange(event.target.value)} className={ownerControlClass}><option value="">All {label.toLowerCase()}s</option>{options.map(([optionValue, optionLabel]) => <option key={optionValue} value={optionValue}>{optionLabel}</option>)}</select></label>; }
function AuditRow({ log, onSelect }: { log: AuditLog; onSelect: (log: AuditLog) => void }) { return <button type="button" onClick={() => onSelect(log)} className="grid w-full gap-2 px-4 py-3.5 text-left transition hover:bg-neutral-50 md:grid-cols-[170px_minmax(190px,1fr)_minmax(170px,1fr)_auto] md:items-center"><time className="text-xs tabular-nums text-neutral-500">{dateTime.format(new Date(log.created_at))}</time><span className="min-w-0"><strong className="block truncate text-sm">{log.action}</strong><span className="block truncate text-xs text-neutral-500">{log.module} · {log.auditable_type}</span></span><span className="min-w-0 text-xs"><strong className="block truncate">{log.actor?.name ?? 'System'}</strong><span className="block truncate text-neutral-500">{log.branch ? `${log.branch.name} · ${log.branch.code}` : 'All branches'}</span></span><OwnerStatusBadge tone="outline">Details</OwnerStatusBadge></button>; }
function EmptyState() { return <div className="px-5 py-16 text-center"><History className="mx-auto mb-3 size-7 text-neutral-300" /><p className="text-sm font-semibold">No audit activity found</p><p className="mt-1 text-sm text-neutral-500">Change or clear a filter to widen the search.</p></div>; }
function AuditDetail({ log, onClose }: { log: AuditLog; onClose: () => void }) { return <Dialog open onOpenChange={(open) => !open && onClose()}><DialogContent className="max-h-[90dvh] max-w-2xl overflow-y-auto p-5"><History className="size-5 text-neutral-500" /><DialogTitle>{log.action}</DialogTitle><DialogDescription>{dateTime.format(new Date(log.created_at))} · {log.auditable_type} {log.auditable_id}</DialogDescription><AuditBlock label="Before" value={log.before} /><AuditBlock label="After" value={log.after} /><AuditBlock label="Metadata" value={log.metadata} /></DialogContent></Dialog>; }
function AuditBlock({ label, value }: { label: string; value: Record<string, unknown> | null }) { return <section><p className="mb-1 text-[10px] font-semibold tracking-[.08em] text-neutral-500 uppercase">{label}</p><pre className="overflow-x-auto rounded-xl bg-neutral-950 p-3 text-xs leading-5 text-neutral-100">{JSON.stringify(value ?? {}, null, 2)}</pre></section>; }
function Pagination({ links }: { links: PageLink[] }) { const previousUrl = links[0]?.url; const nextUrl = links.at(-1)?.url; return <div className="flex items-center justify-between border-t border-neutral-100 p-3"><button type="button" disabled={!previousUrl} onClick={() => previousUrl && router.get(previousUrl)} className={ownerSecondaryActionClass}><ChevronLeft className="mr-1 inline size-4" /> Previous</button><button type="button" disabled={!nextUrl} onClick={() => nextUrl && router.get(nextUrl)} className={ownerSecondaryActionClass}>Next <ChevronRight className="ml-1 inline size-4" /></button></div>; }
