import { Form, Head, router } from '@inertiajs/react';
import { CheckCircle2, ChevronLeft, ChevronRight, KeyRound, Search, ShieldBan } from 'lucide-react';
import { useMemo, useState } from 'react';
import { OwnerPage, OwnerStatusBadge, ownerControlClass, ownerPanelClass, ownerPrimaryActionClass, ownerSecondaryActionClass } from '@/components/owner-ui';
import { Dialog, DialogContent, DialogDescription, DialogTitle } from '@/components/ui/dialog';
import { useAuditRealtimeRefresh } from '@/hooks/use-audit-realtime-refresh';
import { update as updateVoidPin } from '@/routes/workspaces/void-orders/pin';
import { voidOrders } from '@/routes/workspaces';

type Person = { id: number; name: string; email: string };
type VoidRow = { id: string; created_at: string; branch: { id: string; name: string; code: string } | null; order: { id: string; order_number: string; reference_number: string; customer_label: string | null; total: string } | null; initiated_by: Person | null; authorized_by: Person | null; reason_code: string; reason_label: string; reason_text: string | null; authorization_method: string; audit: { id: string; created_at: string; before: Record<string, unknown> | null; after: Record<string, unknown> | null; metadata: Record<string, unknown> | null } | null };
type PageLink = { url: string | null; label: string; active: boolean };
type PinStatus = { configured_at: string; configured_by: Person | null } | null;
type Props = { voids: { data: VoidRow[]; links: PageLink[]; total: number }; filters: Record<string, string>; branches: { id: string; name: string; code: string }[]; users: Person[]; pinStatus: PinStatus };

const reasons: [string, string][] = [['wrong_item', 'Wrong item'], ['customer_cancelled', 'Customer cancelled'], ['duplicate_transaction', 'Duplicate transaction'], ['price_or_quantity_error', 'Price / quantity error'], ['other', 'Other']];
const dateTime = new Intl.DateTimeFormat('en-PH', { dateStyle: 'medium', timeStyle: 'short', timeZone: 'Asia/Manila' });

export default function VoidOrders({ voids, filters, branches, users, pinStatus }: Props) {
    const [selected, setSelected] = useState<VoidRow | null>(null);
    const [search, setSearch] = useState(filters.search ?? '');
    const realtimeProps = useMemo(() => ['voids', 'pinStatus'], []);
    useAuditRealtimeRefresh(realtimeProps);
    const apply = (next: Record<string, string>) => router.get(voidOrders(), { ...filters, ...next }, { preserveScroll: true, replace: true });

    return <><Head title="Void orders" /><OwnerPage title="Void orders" description="Set the approval PIN and monitor every voided sale in one consistent Super Admin workspace.">
        <section className="grid gap-3 xl:grid-cols-[minmax(0,1.6fr)_minmax(340px,0.9fr)]"><VoidRegister voids={voids} filters={filters} branches={branches} users={users} search={search} setSearch={setSearch} apply={apply} onSelect={setSelected} /><PinPanel pinStatus={pinStatus} /></section>
    </OwnerPage>{selected && <VoidDetail record={selected} onClose={() => setSelected(null)} />}</>;
}

function VoidRegister({ voids, filters, branches, users, search, setSearch, apply, onSelect }: { voids: Props['voids']; filters: Record<string, string>; branches: Props['branches']; users: Person[]; search: string; setSearch: (value: string) => void; apply: (next: Record<string, string>) => void; onSelect: (record: VoidRow) => void }) {
    const clear = () => { setSearch(''); router.get(voidOrders(), {}, { preserveScroll: true, replace: true }); };
    return <div className="flex min-w-0 flex-col gap-3"><section className={`${ownerPanelClass} p-3 md:p-4`}><form className="flex flex-col gap-3" onSubmit={(event) => { event.preventDefault(); apply({ search }); }}><div className="flex flex-col gap-2 sm:flex-row"><label className="relative min-w-0 flex-1"><Search className="pointer-events-none absolute top-1/2 left-3 size-4 -translate-y-1/2 text-neutral-400" /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search order number, reference, or staff" className={`${ownerControlClass} w-full pl-10`} /></label><button type="submit" className={ownerSecondaryActionClass}>Search</button><button type="button" onClick={clear} className={ownerSecondaryActionClass}>Clear</button></div><div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-3"><Select label="Branch" value={filters.branch_id ?? ''} options={branches.map((branch) => [branch.id, `${branch.name} · ${branch.code}`])} onChange={(branch_id) => apply({ branch_id })} /><Select label="Initiated by" value={filters.initiated_by_user_id ?? ''} options={users.map((user) => [String(user.id), user.name])} onChange={(initiated_by_user_id) => apply({ initiated_by_user_id })} /><Select label="PIN configured by" value={filters.authorized_by_user_id ?? ''} options={users.map((user) => [String(user.id), user.name])} onChange={(authorized_by_user_id) => apply({ authorized_by_user_id })} /><Select label="Reason" value={filters.reason_code ?? ''} options={reasons} onChange={(reason_code) => apply({ reason_code })} /><label className="grid gap-1 text-[11px] font-semibold text-neutral-600">Date<input type="date" value={filters.date ?? ''} onChange={(event) => apply({ date: event.target.value })} className={ownerControlClass} /></label></div></form></section>
        <section className={`${ownerPanelClass} overflow-hidden`}><div className="flex items-center justify-between gap-3 border-b border-neutral-100 px-4 py-3"><div><p className="text-sm font-semibold">Void register</p><p className="text-xs text-neutral-500">{voids.total} recorded voids · live updates enabled</p></div><OwnerStatusBadge tone="red">Voided</OwnerStatusBadge></div>{voids.data.length === 0 ? <div className="px-5 py-16 text-center text-sm text-neutral-500">No Void records match these filters.</div> : <div className="divide-y divide-neutral-100">{voids.data.map((record) => <button type="button" key={record.id} onClick={() => onSelect(record)} className="grid w-full gap-2 px-4 py-3.5 text-left transition hover:bg-red-50/40 md:grid-cols-[145px_1fr_1fr_auto] md:items-center"><time className="text-xs tabular-nums text-neutral-500">{dateTime.format(new Date(record.created_at))}</time><span><strong className="block text-sm">#{record.order?.order_number ?? 'Deleted order'}</strong><span className="block text-xs text-neutral-500">{record.branch?.name ?? 'No branch'} · {record.reason_label}</span></span><span className="text-xs"><strong className="block truncate">Voided by: {record.initiated_by?.name ?? 'Unknown'}</strong><span className="block truncate text-neutral-500">PIN set by: {record.authorized_by?.name ?? 'Unknown'}</span></span><OwnerStatusBadge tone="red">View</OwnerStatusBadge></button>)}</div>}<Pagination links={voids.links} /></section></div>;
}

function PinPanel({ pinStatus }: { pinStatus: PinStatus }) { return <section className={`${ownerPanelClass} h-fit p-4`}><div className="flex items-start gap-3"><span className="flex size-10 shrink-0 items-center justify-center rounded-xl bg-neutral-950 text-white"><KeyRound className="size-5" /></span><div><h2 className="text-base font-bold">Void approval PIN</h2><p className="mt-1 text-xs leading-5 text-neutral-500">Super Admin sets the 4-digit PIN here. Cashiers use it only when confirming a Void.</p></div></div><div className="my-4 rounded-xl border border-neutral-200 bg-neutral-50 p-3 text-xs"><p className="font-semibold">{pinStatus ? 'PIN is active' : 'PIN is not configured'}</p><p className="mt-1 text-neutral-500">{pinStatus ? `Last set by ${pinStatus.configured_by?.name ?? 'a removed user'} · ${dateTime.format(new Date(pinStatus.configured_at))}` : 'Set a PIN before staff can Void an order.'}</p></div><Form {...updateVoidPin.form()} resetOnSuccess={['pin', 'pin_confirmation']} className="space-y-3">{({ errors, processing }) => <><label className="grid gap-1.5 text-xs font-semibold">New 4-digit PIN<input name="pin" type="password" inputMode="numeric" autoComplete="new-password" pattern="[0-9]{4}" maxLength={4} required className={`${ownerControlClass} text-center text-lg tracking-[0.5em]`} /></label><label className="grid gap-1.5 text-xs font-semibold">Confirm PIN<input name="pin_confirmation" type="password" inputMode="numeric" autoComplete="new-password" pattern="[0-9]{4}" maxLength={4} required className={`${ownerControlClass} text-center text-lg tracking-[0.5em]`} /></label>{(errors.pin || errors.pin_confirmation) && <p role="alert" className="rounded-lg bg-red-50 p-2 text-xs text-red-800">{errors.pin ?? errors.pin_confirmation}</p>}<button type="submit" disabled={processing} className={`${ownerPrimaryActionClass} w-full disabled:opacity-50`}>{processing ? 'Saving…' : pinStatus ? 'Change Void PIN' : 'Set Void PIN'}</button></>}</Form><p className="mt-3 flex gap-1.5 text-[11px] leading-4 text-neutral-500"><CheckCircle2 className="mt-0.5 size-3.5 shrink-0 text-emerald-600" />The PIN is stored securely and never shown in the audit trail.</p></section>; }
function Select({ label, value, options, onChange }: { label: string; value: string; options: [string, string][]; onChange: (value: string) => void }) { return <label className="grid gap-1 text-[11px] font-semibold text-neutral-600">{label}<select value={value} onChange={(event) => onChange(event.target.value)} className={ownerControlClass}><option value="">All</option>{options.map(([optionValue, optionLabel]) => <option key={optionValue} value={optionValue}>{optionLabel}</option>)}</select></label>; }
function VoidDetail({ record, onClose }: { record: VoidRow; onClose: () => void }) { return <Dialog open onOpenChange={(open) => !open && onClose()}><DialogContent className="max-h-[90dvh] max-w-2xl overflow-y-auto p-5"><ShieldBan className="size-5 text-red-700" /><DialogTitle>Void #{record.order?.order_number ?? 'record'}</DialogTitle><DialogDescription>Voided {dateTime.format(new Date(record.created_at))}. The approving identity is the Super Admin who configured the matching PIN.</DialogDescription><dl className="divide-y overflow-hidden rounded-xl border border-neutral-200 text-sm"><Row label="Voided by" value={record.initiated_by ? `${record.initiated_by.name} · ${record.initiated_by.email}` : 'Unknown'} /><Row label="PIN configured by" value={record.authorized_by ? `${record.authorized_by.name} · ${record.authorized_by.email}` : 'Unknown'} /><Row label="Reason" value={record.reason_label} /><Row label="Details" value={record.reason_text ?? '—'} /><Row label="Authorization" value={record.authorization_method} /></dl><pre className="overflow-x-auto rounded-xl bg-neutral-950 p-3 text-xs leading-5 text-neutral-100">{JSON.stringify(record.audit ?? {}, null, 2)}</pre></DialogContent></Dialog>; }
function Row({ label, value }: { label: string; value: string }) { return <div className="flex justify-between gap-3 px-3 py-2"><dt className="text-neutral-500">{label}</dt><dd className="text-right font-semibold">{value}</dd></div>; }
function Pagination({ links }: { links: PageLink[] }) { const previousUrl = links[0]?.url; const nextUrl = links.at(-1)?.url; return <div className="flex justify-between border-t border-neutral-100 p-3"><button type="button" disabled={!previousUrl} onClick={() => previousUrl && router.get(previousUrl)} className={ownerSecondaryActionClass}><ChevronLeft className="mr-1 inline size-4" /> Previous</button><button type="button" disabled={!nextUrl} onClick={() => nextUrl && router.get(nextUrl)} className={ownerSecondaryActionClass}>Next <ChevronRight className="ml-1 inline size-4" /></button></div>; }
