import { Head, router } from '@inertiajs/react';
import { ChevronLeft, ChevronRight, ShieldBan } from 'lucide-react';
import { useState } from 'react';
import { OwnerPage, OwnerStatusBadge, ownerControlClass, ownerPanelClass } from '@/components/owner-ui';
import { Dialog, DialogContent, DialogDescription, DialogTitle } from '@/components/ui/dialog';
import { voidOrders } from '@/routes/workspaces';

type Person = { id: number; name: string; email: string };
type VoidRow = { id: string; created_at: string; branch: { id: string; name: string; code: string } | null; order: { id: string; order_number: string; reference_number: string; customer_label: string | null; total: string } | null; initiated_by: Person | null; authorized_by: Person | null; reason_code: string; reason_label: string; reason_text: string | null; authorization_method: string; audit: { id: string; created_at: string; before: Record<string, unknown> | null; after: Record<string, unknown> | null; metadata: Record<string, unknown> | null } | null };
type Link = { url: string | null; label: string; active: boolean };
type Props = { voids: { data: VoidRow[]; links: Link[]; total: number }; filters: Record<string, string>; branches: { id: string; name: string; code: string }[]; users: Person[] };
const dateTime = new Intl.DateTimeFormat('en-PH', { dateStyle: 'medium', timeStyle: 'short', timeZone: 'Asia/Manila' });
const reasons = [['wrong_item', 'Wrong item'], ['customer_cancelled', 'Customer cancelled'], ['duplicate_transaction', 'Duplicate transaction'], ['price_or_quantity_error', 'Price / quantity error'], ['other', 'Other']];

export default function VoidOrders({ voids, filters, branches, users }: Props) {
    const [selected, setSelected] = useState<VoidRow | null>(null);
    const apply = (next: Record<string, string>) => router.get(voidOrders(), { ...filters, ...next }, { preserveScroll: true, replace: true });
    return <><Head title="Void orders" /><OwnerPage title="Void orders" description="Read-only Void register. Every record shows the required two-person authorization and its immutable audit entry.">
        <section className={`${ownerPanelClass} grid gap-2 p-3 sm:grid-cols-2 lg:grid-cols-5`}>
            <Select label="Branch" value={filters.branch_id ?? ''} options={branches.map((branch) => [branch.id, `${branch.name} · ${branch.code}`])} onChange={(branch_id) => apply({ branch_id })} />
            <Select label="Initiated by" value={filters.initiated_by_user_id ?? ''} options={users.map((user) => [String(user.id), user.name])} onChange={(initiated_by_user_id) => apply({ initiated_by_user_id })} />
            <Select label="Authorized by" value={filters.authorized_by_user_id ?? ''} options={users.map((user) => [String(user.id), user.name])} onChange={(authorized_by_user_id) => apply({ authorized_by_user_id })} />
            <Select label="Reason" value={filters.reason_code ?? ''} options={reasons} onChange={(reason_code) => apply({ reason_code })} />
            <label className="grid gap-1 text-[11px] font-semibold text-neutral-600">Date<input type="date" value={filters.date ?? ''} onChange={(event) => apply({ date: event.target.value })} className={ownerControlClass} /></label>
            <button type="button" onClick={() => router.get(voidOrders(), {}, { preserveScroll: true, replace: true })} className="min-h-11 rounded-[11px] border border-neutral-200 text-xs font-semibold sm:col-span-2 lg:col-span-5">Clear filters</button>
        </section>
        <section className={`${ownerPanelClass} overflow-hidden`}><div className="border-b border-neutral-100 px-4 py-3 text-sm font-semibold">{voids.total} void records</div>{voids.data.length === 0 ? <div className="px-5 py-16 text-center text-sm text-neutral-500">No Void records match these filters.</div> : <div className="divide-y divide-neutral-100">{voids.data.map((voidRecord) => <button type="button" key={voidRecord.id} onClick={() => setSelected(voidRecord)} className="grid w-full gap-2 px-4 py-3 text-left hover:bg-red-50/40 md:grid-cols-[150px_1fr_1fr_auto] md:items-center"><span className="text-xs tabular-nums text-neutral-500">{dateTime.format(new Date(voidRecord.created_at))}</span><span><strong className="block text-sm">#{voidRecord.order?.order_number ?? 'Deleted order'}</strong><span className="block text-xs text-neutral-500">{voidRecord.branch?.name ?? 'No branch'} · {voidRecord.reason_label}</span></span><span className="text-xs"><strong className="block">Initiated: {voidRecord.initiated_by?.name ?? 'Unknown'}</strong><span className="block text-neutral-500">Authorized: {voidRecord.authorized_by?.name ?? 'Unknown'}</span></span><OwnerStatusBadge tone="red">Voided</OwnerStatusBadge></button>)}</div>}<Pagination links={voids.links} /></section>
    </OwnerPage>{selected && <VoidDetail record={selected} onClose={() => setSelected(null)} />}</>;
}

function Select({ label, value, options, onChange }: { label: string; value: string; options: string[][]; onChange: (value: string) => void }) { return <label className="grid gap-1 text-[11px] font-semibold text-neutral-600">{label}<select value={value} onChange={(event) => onChange(event.target.value)} className={ownerControlClass}><option value="">All</option>{options.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label>; }
function VoidDetail({ record, onClose }: { record: VoidRow; onClose: () => void }) { return <Dialog open onOpenChange={(open) => !open && onClose()}><DialogContent className="max-h-[90dvh] max-w-2xl overflow-y-auto p-5"><ShieldBan className="size-5 text-red-700" /><DialogTitle>Void #{record.order?.order_number ?? 'record'}</DialogTitle><DialogDescription>Two-person authorization completed {dateTime.format(new Date(record.created_at))}.</DialogDescription><dl className="divide-y overflow-hidden rounded-xl border border-neutral-200 text-sm"><Row label="Initiated by" value={record.initiated_by ? `${record.initiated_by.name} · ${record.initiated_by.email}` : 'Unknown'} /><Row label="Authorized by" value={record.authorized_by ? `${record.authorized_by.name} · ${record.authorized_by.email}` : 'Unknown'} /><Row label="Reason" value={record.reason_label} /><Row label="Details" value={record.reason_text ?? '—'} /><Row label="Authorization" value={record.authorization_method} /></dl><pre className="overflow-x-auto rounded-xl bg-neutral-950 p-3 text-xs leading-5 text-neutral-100">{JSON.stringify(record.audit ?? {}, null, 2)}</pre></DialogContent></Dialog>; }
function Row({ label, value }: { label: string; value: string }) { return <div className="flex justify-between gap-3 px-3 py-2"><dt className="text-neutral-500">{label}</dt><dd className="text-right font-semibold">{value}</dd></div>; }
function Pagination({ links }: { links: Link[] }) { const previous = links[0]; const next = links.at(-1); return <div className="flex justify-between border-t border-neutral-100 p-3"><button type="button" disabled={!previous?.url} onClick={() => previous.url && router.get(previous.url)} className="inline-flex h-10 items-center gap-1 rounded-lg border border-neutral-200 px-3 text-xs font-semibold disabled:opacity-40"><ChevronLeft className="size-4" /> Previous</button><button type="button" disabled={!next?.url} onClick={() => next.url && router.get(next.url)} className="inline-flex h-10 items-center gap-1 rounded-lg border border-neutral-200 px-3 text-xs font-semibold disabled:opacity-40">Next <ChevronRight className="size-4" /></button></div>; }
