<?php

namespace App\Models;

use Database\Factories\CustomerScreenMediaFactory;
use Illuminate\Database\Eloquent\Attributes\Fillable;
use Illuminate\Database\Eloquent\Attributes\Hidden;
use Illuminate\Database\Eloquent\Concerns\HasUuids;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Support\Carbon;

/**
 * One Branch advertisement shown on its customer screens while no operating mode is selected. The storage path is
 * generated by the server (`CustomerScreenMediaLibrary`); client file names, paths and MIME claims are never stored.
 *
 * @property string $id
 * @property string $branch_id
 * @property 'image'|'video' $media_type
 * @property string $label
 * @property string $path
 * @property string $mime_type
 * @property int $size_bytes
 * @property int $duration_seconds
 * @property int $sort_order
 * @property bool $is_active
 * @property int|null $created_by_user_id
 * @property Carbon|null $created_at
 * @property Carbon|null $updated_at
 */
#[Fillable(['branch_id', 'media_type', 'label', 'path', 'mime_type', 'size_bytes', 'duration_seconds', 'sort_order', 'is_active', 'created_by_user_id'])]
#[Hidden(['path'])]
class CustomerScreenMedia extends Model
{
    /** @use HasFactory<CustomerScreenMediaFactory> */
    use HasFactory, HasUuids;

    protected $table = 'customer_screen_media';

    /** @return array<string, string> */
    protected function casts(): array
    {
        return [
            'size_bytes' => 'integer',
            'duration_seconds' => 'integer',
            'sort_order' => 'integer',
            'is_active' => 'boolean',
        ];
    }

    /** @return BelongsTo<Branch, $this> */
    public function branch(): BelongsTo
    {
        return $this->belongsTo(Branch::class);
    }
}
